apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-saga
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-saga
  template:
    metadata:
      labels:
        app: postgres-saga
    spec:
      containers:
        - name: postgres-saga
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: saga_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-saga
  namespace: ecommerce
spec:
  selector:
    app: postgres-saga
  ports:
    - port: 5432
      targetPort: 5432