server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
## Usando as configuraçoes locais
      server:
        native:
          search-locations: file:../ecommerce-config/, file:./ecommerce-config/
## Usando as configuracoes do
#      git:
#        uri: https://github.com/immarcosmorais/ecommerce-config
#        default-label: main
#        clone-on-start: true