apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "discovery-server"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: ecommerce
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761